### ISSUE TITLE
Command "sudo docker build -t l4-da" Failing

### ISSUE THREAD

**Issue by jakubbester** [smucclaw/l4-docassemble#6]
I was trying to build the l4-docassemble tool after using the git clone command to clone this repository into my local directory. After running the command `sudo docker build -t l4-da .` as specified by the documentation, the code manages to download, extract, and build everything up until Step #11, and then it fails. Below is an image of the error that is occurring.

![image](https://user-images.githubusercontent.com/45968528/208001263-763aa6fc-156c-40c7-8788-3ba4124e829c.png)

My group did take a look and try to resolve the issue ourselves, and we managed to install all of the three python packages by directly getting into the www-data and root users and installing the correct python version (since it's expecting python3.8 whereas the current/latest Docassemble code is using python3.10). However, after booting up Docassemble in the localhost, we found that although the three packages `docassemble-datatypes`, `docassemble-scasp`, and `docassemble-l4` were installed, the code was still failing by saying that it cannot find them. Below is an image of the error occuring.

![image](https://user-images.githubusercontent.com/45968528/208001295-26dc959e-8b6d-41c6-8d64-54ce0da61072.png)

These are the errors that we received after booting up the three examples in this GitHub repository. As can be seen, from a series of commands (first image), we were able to get it so that the three files are found (as well as the pgf Python package that we were having trouble with, getting an error that <gu/mem.h> is not found), however when running the corresponding examples, they all failed saying the packages are not found (second image). **Note:** We checked to make sure that updating the packages throws no error (third image).

![image](https://user-images.githubusercontent.com/45968528/208001857-5611121f-c9df-423f-9ed5-f307cd610b0c.png)

![image](https://user-images.githubusercontent.com/45968528/208001770-116d2319-0600-460f-89ce-08bbd9acb35b.png)

![image](https://user-images.githubusercontent.com/45968528/208002193-2b74806b-844a-40d7-8cc1-5704e923cdb8.png)

**Comment by kharus** [comment]
Hi @jakubbester.
Let me have a look.
I think root cause is in Dockerfile latest version of DA is used
`FROM jhpyle/docassemble:latest`
We haven't look at this project at CCLAW for last 1.5 years, so underlying versions have drifted.

**Comment by kharus** [comment]
Hi @jakubbester .

I found an old working image.
So in readme instead of
```bash
docker run -d -p 80:80 -p 443:443 --stop-timeout 600 l4-da
```
Please run
```
docker run -d -p 80:80 -p 443:443 --stop-timeout 600 kharu5/l4-da:v0.0.1
```
This will pull working image I created.

**Comment by jakubbester** [comment]
Hello @kharus

Thank you kindly for the help. This worked well. We are excited to be presenting the tool!

I am closing this thread.
